### ISSUE TITLE
Range And Bearing edition

### ISSUE THREAD

**Issue by popoleeMaster** [articodeltd/angular-cesium#265] opened 2019-04-15 09:04 UTC
Is there a way to make the range and bearing component stop and pass in edit mode?

Right now what I manage to do is 

1) you can draw infinitely, and if you call dispose it disappear.
2) you set a maximum number of line, but this doesn't work if you want a user to make a path with start and end on different length
3) draw an infinite path and save it with the observable, when the user say "I ended my path" dispose of that path and create another path using the saved variable and setting the max length to what the path is. 

also, I noticed the range and bearing is not editable (yet?).

**Comment by eitanfr** [comment] 2019-04-15 09:46
Not sure I understood your question.
`range-and-bearing` is editable after the lines are created, checkout the demo: http://www.angular-cesium.com.

`range-and-bearing` is our implementation for a measuring tool, it can be configurable with `RangeAndBearingOptions` you pass to the `create()` method. 
Any way `range-and-bearing` implemented with the `PolylineEditor`, so you always can create a component that uses the editor that will be more suitable for your needs.

**Comment by popoleeMaster** [comment] 2019-04-15 09:55
@eitanfr thank for the reply, sorry if it is not precise enough.

The problem I have is PolylineEditorService (and the RandeAndBearing) have no method to end the path.

The only way to end a path is to click on the starting point or set a maximum size of point per path.

What would be cool is to and a create() and a end(), when I call end() the path is locked with the current amount of point and can be edited only.

I checked the demo of RandeAndBearing, but I do not understand how you close/end the path. In the demo when I click on the ruler, the only way to stop creating point is to delete the path by clicking again the ruler.

Anyway yes, I copied the code and I am trying to modify to suit my need. If I make something decent I will PR probably if you would like to have the change.

**Comment by popoleeMaster** [comment] 2019-04-16 05:41
well here is a quick change I made that work in my case and explain my request better maybe, 

I Added in polyline service the following : 

```
  close(polyline$: PolylineEditorObservable, switchToEditMode: boolean) {
    const id = obs.getEditValue().id;
    const polyline = this.polylinesManager.get(id);

    if (!polyline) {
      return;
    }
    if (switchToEditMode) {
      const finish = this.switchToEditMode(
        id,
        [polyline.positions - 1],
        polyline$,
        polyline.positions,
        100,
        polyline.editOptions,
        polyline$,
        finish
      );
    } else {
      const observables = this.observablesMap.get(id);
      if (observables) {
        observables.forEach(obs => obs.dispose());
      }
    }
  }
```

So that I can close a path and select if just close the path so no longer editable, or if you just disable new point and edit the current path.

There is other change to be made, but for the moment I need to do a demo for other stuff so is just a quick way for explaining you better I hope.

**Comment by eitanfr** [comment] 2019-04-20 17:26
I think I understand what are you trying to achieve,
When you create an editable polyline you want the option to change the drawing state from `create` to `edit` programmatically.
Indeed this option is currently missing, currently only when you do double click (or any event you chose) line creation considered as done and you move to edit mode. 

Therefore I would add the missing functionality to the `PolylineEditorObservable`, so you could do something like: 
```typescript
const editing$ = this.polylineEditor.create();
// later
editing$.finish()
``` 
It would be great if you could open a PR for it, I will be happy to guide you if you have questions.

**Comment by popoleeMaster** [comment] 2019-04-24 03:53
I made a lot of changes in my personal project, I have some deadlines to handle and no time to clean and PR. But, has soon as I find some, I will.

**Comment by kevinleary** [comment] 2019-12-04 21:15
I also wanted to work on some range and bearing additions to make it more consistently like the other draw tools. One question I have is that why is the Range and Bearing tool not a editable `AcEntity` like the rest of the draw tools?

**Comment by anotherhale** [comment] 2019-12-18 00:47
I was able to get some additional features with my [Custom Range and Bearing component](https://gist.github.com/anotherhale/6fba39d1342abfa6f3d18ad235d17374).   I too wanted to have the ability to have multiple RnB components, but the issue is that the `PolylinesManagerService` is not exported publicly. I am about to open a PR to expose all of the `entity-editors` `ManagerService`s to allow for custom components to access the API.

**Comment by eitanfr** [comment] 2019-12-19 09:37
> I was able to get some additional features with my [Custom Range and Bearing component](https://gist.github.com/anotherhale/6fba39d1342abfa6f3d18ad235d17374). I too wanted to have the ability to have multiple RnB components, but the issue is that the `PolylinesManagerService` is not exported publicly. I am about to open a PR to expose all of the `entity-editors` `ManagerService`s to allow for custom components to access the API.
> #319
> Ignore [anotherhale@f9c7747](https://github.com/anotherhale/angular-cesium/commit/f9c7747f07d54edf5e4f817d78585809d8f97d86) I had not pulled latest before committing.

answered in #233.

**Comment by eitanfr** [comment] 2019-12-19 09:40
> I made a lot of changes in my personal project, I have some deadlines to handle and no time to clean and PR. But, has soon as I find some, I will.

@popoleeMaster Looking forward to your PR, closing the issue for now.

**Closed by eitanfr** 2019-12-19 09:40 UTC
