### ISSUE TITLE
Entities not rendering

### ISSUE THREAD

**Issue by mikeallgyer** [articodeltd/angular-cesium#348] opened 2020-04-23 15:38 UTC
**Intended outcome:**
Trying to render simple entities (points and billboards) according to starter tutorial.
**Actual outcome:**
Only globe renders, no stars and no entities. This occurs both in my code and in the stackblitzes supplied in the tutorials.

**How to reproduce the issue:**
Run the following demos:
https://stackblitz.com/edit/angular-cesium-point-example?file=package.json
https://stackblitz.com/edit/angular-cesium-billboard-example?embed=1&file=src/app/billboard-layer-example/billboard-layer-example.component.ts

**Version**
- angular-cesium@0.0.60
- @angular/common@8.0.0
-cesium@1.48.0

**Comment by eitanfr** [comment] 2020-04-28 09:56
Hi!
I tried to run the first stackblitz example and looks like everything works, see attached image.
Does demos from Cesium's sandcastle work for you?
Which kind of browser and OS do you use? maybe a browser issue. 
Also, can you please provide more info? do you have errors in the console?

![image](https://user-images.githubusercontent.com/9163916/80473638-166ec000-894f-11ea-9cf4-dead778edbc5.png)

**Comment by mikeallgyer** [comment] 2020-04-28 13:16
Thanks for your reply! 

I'm seeing a bunch of terrain-related console errors like this in Chrome 81:

Failed to load resource: net::ERR_FAILED
www.angular-cesium.com/assets/cesium/Assets/approximateTerrainHeights.json:1 Failed to load resource: net::ERR_FAILED

Tested in Chrome 81, Firefox 75, Edge 44.. I get similar errors in chrome and firefox (globe with no points) and memory exceptions in edge (no globe). cesium sandcastle works everywhere just fine.

pc config
windows 10
intel i7
32 gb ram
nvidia geforce 1080ti

also tested on other machines (all windows) with same results.

**Comment by eitanfr** [comment] 2020-04-30 09:49
Mmm seems like an issue with stackblitz demo's and how they load cesium, because of how stackblitz work the way Cesium is loaded is hacky (we load the assets from angular-cesium.com website).
did you follow the getting started tutorial and tried to run locally?  if so, did you have any errors?

**Comment by mikeallgyer** [comment] 2020-05-01 13:31
interesting. yeah i was trying to get it working locally without much luck and then when the demo didn't work either i got discouraged haha. i don't think i had any errors, and unfortunately due to time constraints i had to move on so i'm basically using the standard cesium api now.

**Comment by ASEG-ASmith** [comment] 2020-05-13 19:07
I seem to be seeing the same issue.  The only thing I see on stackblitz demos is the globe; I tried the polyline and billboard demos.  I have tried locally also and get the same results - just the globe.
I've tried locally on latest stable versions of firefox and chrome with angular-cesium 0.0.66 and cesium 1.69.0.  I tried the stackblitz demos on firefox and chrome on Windows 10 and centos.  Same empty globe in all cases.  The viewers in the following links do seem to work: https://angular-cesium.com and https://angular-cesium.herokuapp.com/.

**Comment by eitanfr** [comment] 2020-05-15 15:47
After further investigating the issue, it seems there was a CORS issue with the stackblitz issue.
All the stackblitz demos are fixed now, please let me know if you still having issues @mikeallgyer @ASEG-ASmith 

Also, I want to make it clear that the stackblitz demos load cesium assets in a hacky way because of stackblitz limitations (we load cesium assets from another host). The right way to do it is to host cesium assets by yourself as explained in the getting-started guide.

**Comment by ASEG-ASmith** [comment] 2020-05-15 17:18
Yes I can confirm see the content on stackblitz demos - thanks for the follow-up.

**Comment by eitanfr** [comment] 2020-05-18 12:06
Great!

**Closed by eitanfr** 2020-05-18 12:06 UTC
